from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.get_api_users_offset200_response_users_inner import GetApiUsersOffset200ResponseUsersInner
from openapi_server import util

from openapi_server.models.get_api_users_offset200_response_users_inner import GetApiUsersOffset200ResponseUsersInner  # noqa: E501

class GetApiUsersOffset200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, users=None):  # noqa: E501
        """GetApiUsersOffset200Response - a model defined in OpenAPI

        :param users: The users of this GetApiUsersOffset200Response.  # noqa: E501
        :type users: List[GetApiUsersOffset200ResponseUsersInner]
        """
        self.openapi_types = {
            'users': List[GetApiUsersOffset200ResponseUsersInner]
        }

        self.attribute_map = {
            'users': 'users'
        }

        self._users = users

    @classmethod
    def from_dict(cls, dikt) -> 'GetApiUsersOffset200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The getApiUsersOffset_200_response of this GetApiUsersOffset200Response.  # noqa: E501
        :rtype: GetApiUsersOffset200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def users(self) -> List[GetApiUsersOffset200ResponseUsersInner]:
        """Gets the users of this GetApiUsersOffset200Response.


        :return: The users of this GetApiUsersOffset200Response.
        :rtype: List[GetApiUsersOffset200ResponseUsersInner]
        """
        return self._users

    @users.setter
    def users(self, users: List[GetApiUsersOffset200ResponseUsersInner]):
        """Sets the users of this GetApiUsersOffset200Response.


        :param users: The users of this GetApiUsersOffset200Response.
        :type users: List[GetApiUsersOffset200ResponseUsersInner]
        """
        if users is None:
            raise ValueError("Invalid value for `users`, must not be `None`")  # noqa: E501

        self._users = users
