from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class GetApiUsersOffset200ResponseUsersInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, email=None, username=None, first_name=None, last_name=None, dob=None, role=None, created_at=None, updated_at=None):  # noqa: E501
        """GetApiUsersOffset200ResponseUsersInner - a model defined in OpenAPI

        :param id: The id of this GetApiUsersOffset200ResponseUsersInner.  # noqa: E501
        :type id: int
        :param email: The email of this GetApiUsersOffset200ResponseUsersInner.  # noqa: E501
        :type email: str
        :param username: The username of this GetApiUsersOffset200ResponseUsersInner.  # noqa: E501
        :type username: str
        :param first_name: The first_name of this GetApiUsersOffset200ResponseUsersInner.  # noqa: E501
        :type first_name: str
        :param last_name: The last_name of this GetApiUsersOffset200ResponseUsersInner.  # noqa: E501
        :type last_name: str
        :param dob: The dob of this GetApiUsersOffset200ResponseUsersInner.  # noqa: E501
        :type dob: str
        :param role: The role of this GetApiUsersOffset200ResponseUsersInner.  # noqa: E501
        :type role: str
        :param created_at: The created_at of this GetApiUsersOffset200ResponseUsersInner.  # noqa: E501
        :type created_at: str
        :param updated_at: The updated_at of this GetApiUsersOffset200ResponseUsersInner.  # noqa: E501
        :type updated_at: str
        """
        self.openapi_types = {
            'id': int,
            'email': str,
            'username': str,
            'first_name': str,
            'last_name': str,
            'dob': str,
            'role': str,
            'created_at': str,
            'updated_at': str
        }

        self.attribute_map = {
            'id': 'id',
            'email': 'email',
            'username': 'username',
            'first_name': 'first_name',
            'last_name': 'last_name',
            'dob': 'dob',
            'role': 'role',
            'created_at': 'created_at',
            'updated_at': 'updated_at'
        }

        self._id = id
        self._email = email
        self._username = username
        self._first_name = first_name
        self._last_name = last_name
        self._dob = dob
        self._role = role
        self._created_at = created_at
        self._updated_at = updated_at

    @classmethod
    def from_dict(cls, dikt) -> 'GetApiUsersOffset200ResponseUsersInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The getApiUsersOffset_200_response_users_inner of this GetApiUsersOffset200ResponseUsersInner.  # noqa: E501
        :rtype: GetApiUsersOffset200ResponseUsersInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this GetApiUsersOffset200ResponseUsersInner.


        :return: The id of this GetApiUsersOffset200ResponseUsersInner.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this GetApiUsersOffset200ResponseUsersInner.


        :param id: The id of this GetApiUsersOffset200ResponseUsersInner.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501
        if id is not None and id > 9007199254740991:  # noqa: E501
            raise ValueError("Invalid value for `id`, must be a value less than or equal to `9007199254740991`")  # noqa: E501
        if id is not None and id < -9007199254740991:  # noqa: E501
            raise ValueError("Invalid value for `id`, must be a value greater than or equal to `-9007199254740991`")  # noqa: E501

        self._id = id

    @property
    def email(self) -> str:
        """Gets the email of this GetApiUsersOffset200ResponseUsersInner.


        :return: The email of this GetApiUsersOffset200ResponseUsersInner.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this GetApiUsersOffset200ResponseUsersInner.


        :param email: The email of this GetApiUsersOffset200ResponseUsersInner.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def username(self) -> str:
        """Gets the username of this GetApiUsersOffset200ResponseUsersInner.


        :return: The username of this GetApiUsersOffset200ResponseUsersInner.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this GetApiUsersOffset200ResponseUsersInner.


        :param username: The username of this GetApiUsersOffset200ResponseUsersInner.
        :type username: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def first_name(self) -> str:
        """Gets the first_name of this GetApiUsersOffset200ResponseUsersInner.


        :return: The first_name of this GetApiUsersOffset200ResponseUsersInner.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name: str):
        """Sets the first_name of this GetApiUsersOffset200ResponseUsersInner.


        :param first_name: The first_name of this GetApiUsersOffset200ResponseUsersInner.
        :type first_name: str
        """
        if first_name is None:
            raise ValueError("Invalid value for `first_name`, must not be `None`")  # noqa: E501

        self._first_name = first_name

    @property
    def last_name(self) -> str:
        """Gets the last_name of this GetApiUsersOffset200ResponseUsersInner.


        :return: The last_name of this GetApiUsersOffset200ResponseUsersInner.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name: str):
        """Sets the last_name of this GetApiUsersOffset200ResponseUsersInner.


        :param last_name: The last_name of this GetApiUsersOffset200ResponseUsersInner.
        :type last_name: str
        """
        if last_name is None:
            raise ValueError("Invalid value for `last_name`, must not be `None`")  # noqa: E501

        self._last_name = last_name

    @property
    def dob(self) -> str:
        """Gets the dob of this GetApiUsersOffset200ResponseUsersInner.


        :return: The dob of this GetApiUsersOffset200ResponseUsersInner.
        :rtype: str
        """
        return self._dob

    @dob.setter
    def dob(self, dob: str):
        """Sets the dob of this GetApiUsersOffset200ResponseUsersInner.


        :param dob: The dob of this GetApiUsersOffset200ResponseUsersInner.
        :type dob: str
        """
        if dob is None:
            raise ValueError("Invalid value for `dob`, must not be `None`")  # noqa: E501

        self._dob = dob

    @property
    def role(self) -> str:
        """Gets the role of this GetApiUsersOffset200ResponseUsersInner.


        :return: The role of this GetApiUsersOffset200ResponseUsersInner.
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role: str):
        """Sets the role of this GetApiUsersOffset200ResponseUsersInner.


        :param role: The role of this GetApiUsersOffset200ResponseUsersInner.
        :type role: str
        """
        allowed_values = ["admin", "operator", "user"]  # noqa: E501
        if role not in allowed_values:
            raise ValueError(
                "Invalid value for `role` ({0}), must be one of {1}"
                .format(role, allowed_values)
            )

        self._role = role

    @property
    def created_at(self) -> str:
        """Gets the created_at of this GetApiUsersOffset200ResponseUsersInner.


        :return: The created_at of this GetApiUsersOffset200ResponseUsersInner.
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: str):
        """Sets the created_at of this GetApiUsersOffset200ResponseUsersInner.


        :param created_at: The created_at of this GetApiUsersOffset200ResponseUsersInner.
        :type created_at: str
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def updated_at(self) -> str:
        """Gets the updated_at of this GetApiUsersOffset200ResponseUsersInner.


        :return: The updated_at of this GetApiUsersOffset200ResponseUsersInner.
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: str):
        """Sets the updated_at of this GetApiUsersOffset200ResponseUsersInner.


        :param updated_at: The updated_at of this GetApiUsersOffset200ResponseUsersInner.
        :type updated_at: str
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")  # noqa: E501

        self._updated_at = updated_at
