from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.post_api_users_by_id_addresses_request_is_default import PostApiUsersByIdAddressesRequestIsDefault
from openapi_server import util

from openapi_server.models.post_api_users_by_id_addresses_request_is_default import PostApiUsersByIdAddressesRequestIsDefault  # noqa: E501

class PatchApiUsersByIdAddressesByAddressIdRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, user_id=None, address=None, phone=None, state=None, postal_code=None, country=None, is_default=None, created_at=None, updated_at=None):  # noqa: E501
        """PatchApiUsersByIdAddressesByAddressIdRequest - a model defined in OpenAPI

        :param id: The id of this PatchApiUsersByIdAddressesByAddressIdRequest.  # noqa: E501
        :type id: int
        :param user_id: The user_id of this PatchApiUsersByIdAddressesByAddressIdRequest.  # noqa: E501
        :type user_id: int
        :param address: The address of this PatchApiUsersByIdAddressesByAddressIdRequest.  # noqa: E501
        :type address: str
        :param phone: The phone of this PatchApiUsersByIdAddressesByAddressIdRequest.  # noqa: E501
        :type phone: str
        :param state: The state of this PatchApiUsersByIdAddressesByAddressIdRequest.  # noqa: E501
        :type state: str
        :param postal_code: The postal_code of this PatchApiUsersByIdAddressesByAddressIdRequest.  # noqa: E501
        :type postal_code: str
        :param country: The country of this PatchApiUsersByIdAddressesByAddressIdRequest.  # noqa: E501
        :type country: str
        :param is_default: The is_default of this PatchApiUsersByIdAddressesByAddressIdRequest.  # noqa: E501
        :type is_default: PostApiUsersByIdAddressesRequestIsDefault
        :param created_at: The created_at of this PatchApiUsersByIdAddressesByAddressIdRequest.  # noqa: E501
        :type created_at: str
        :param updated_at: The updated_at of this PatchApiUsersByIdAddressesByAddressIdRequest.  # noqa: E501
        :type updated_at: str
        """
        self.openapi_types = {
            'id': int,
            'user_id': int,
            'address': str,
            'phone': str,
            'state': str,
            'postal_code': str,
            'country': str,
            'is_default': PostApiUsersByIdAddressesRequestIsDefault,
            'created_at': str,
            'updated_at': str
        }

        self.attribute_map = {
            'id': 'id',
            'user_id': 'user_id',
            'address': 'address',
            'phone': 'phone',
            'state': 'state',
            'postal_code': 'postal_code',
            'country': 'country',
            'is_default': 'is_default',
            'created_at': 'created_at',
            'updated_at': 'updated_at'
        }

        self._id = id
        self._user_id = user_id
        self._address = address
        self._phone = phone
        self._state = state
        self._postal_code = postal_code
        self._country = country
        self._is_default = is_default
        self._created_at = created_at
        self._updated_at = updated_at

    @classmethod
    def from_dict(cls, dikt) -> 'PatchApiUsersByIdAddressesByAddressIdRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The patchApiUsersByIdAddressesByAddress_id_request of this PatchApiUsersByIdAddressesByAddressIdRequest.  # noqa: E501
        :rtype: PatchApiUsersByIdAddressesByAddressIdRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this PatchApiUsersByIdAddressesByAddressIdRequest.


        :return: The id of this PatchApiUsersByIdAddressesByAddressIdRequest.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this PatchApiUsersByIdAddressesByAddressIdRequest.


        :param id: The id of this PatchApiUsersByIdAddressesByAddressIdRequest.
        :type id: int
        """
        if id is not None and id > 9007199254740991:  # noqa: E501
            raise ValueError("Invalid value for `id`, must be a value less than or equal to `9007199254740991`")  # noqa: E501
        if id is not None and id < -9007199254740991:  # noqa: E501
            raise ValueError("Invalid value for `id`, must be a value greater than or equal to `-9007199254740991`")  # noqa: E501

        self._id = id

    @property
    def user_id(self) -> int:
        """Gets the user_id of this PatchApiUsersByIdAddressesByAddressIdRequest.


        :return: The user_id of this PatchApiUsersByIdAddressesByAddressIdRequest.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this PatchApiUsersByIdAddressesByAddressIdRequest.


        :param user_id: The user_id of this PatchApiUsersByIdAddressesByAddressIdRequest.
        :type user_id: int
        """
        if user_id is not None and user_id > 9007199254740991:  # noqa: E501
            raise ValueError("Invalid value for `user_id`, must be a value less than or equal to `9007199254740991`")  # noqa: E501
        if user_id is not None and user_id < -9007199254740991:  # noqa: E501
            raise ValueError("Invalid value for `user_id`, must be a value greater than or equal to `-9007199254740991`")  # noqa: E501

        self._user_id = user_id

    @property
    def address(self) -> str:
        """Gets the address of this PatchApiUsersByIdAddressesByAddressIdRequest.


        :return: The address of this PatchApiUsersByIdAddressesByAddressIdRequest.
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address: str):
        """Sets the address of this PatchApiUsersByIdAddressesByAddressIdRequest.


        :param address: The address of this PatchApiUsersByIdAddressesByAddressIdRequest.
        :type address: str
        """
        if address is not None and len(address) > 255:
            raise ValueError("Invalid value for `address`, length must be less than or equal to `255`")  # noqa: E501
        if address is not None and len(address) < 5:
            raise ValueError("Invalid value for `address`, length must be greater than or equal to `5`")  # noqa: E501

        self._address = address

    @property
    def phone(self) -> str:
        """Gets the phone of this PatchApiUsersByIdAddressesByAddressIdRequest.


        :return: The phone of this PatchApiUsersByIdAddressesByAddressIdRequest.
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone: str):
        """Sets the phone of this PatchApiUsersByIdAddressesByAddressIdRequest.


        :param phone: The phone of this PatchApiUsersByIdAddressesByAddressIdRequest.
        :type phone: str
        """
        if phone is not None and len(phone) > 10:
            raise ValueError("Invalid value for `phone`, length must be less than or equal to `10`")  # noqa: E501

        self._phone = phone

    @property
    def state(self) -> str:
        """Gets the state of this PatchApiUsersByIdAddressesByAddressIdRequest.


        :return: The state of this PatchApiUsersByIdAddressesByAddressIdRequest.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state: str):
        """Sets the state of this PatchApiUsersByIdAddressesByAddressIdRequest.


        :param state: The state of this PatchApiUsersByIdAddressesByAddressIdRequest.
        :type state: str
        """
        if state is not None and len(state) > 100:
            raise ValueError("Invalid value for `state`, length must be less than or equal to `100`")  # noqa: E501

        self._state = state

    @property
    def postal_code(self) -> str:
        """Gets the postal_code of this PatchApiUsersByIdAddressesByAddressIdRequest.


        :return: The postal_code of this PatchApiUsersByIdAddressesByAddressIdRequest.
        :rtype: str
        """
        return self._postal_code

    @postal_code.setter
    def postal_code(self, postal_code: str):
        """Sets the postal_code of this PatchApiUsersByIdAddressesByAddressIdRequest.


        :param postal_code: The postal_code of this PatchApiUsersByIdAddressesByAddressIdRequest.
        :type postal_code: str
        """
        if postal_code is not None and len(postal_code) > 20:
            raise ValueError("Invalid value for `postal_code`, length must be less than or equal to `20`")  # noqa: E501

        self._postal_code = postal_code

    @property
    def country(self) -> str:
        """Gets the country of this PatchApiUsersByIdAddressesByAddressIdRequest.


        :return: The country of this PatchApiUsersByIdAddressesByAddressIdRequest.
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country: str):
        """Sets the country of this PatchApiUsersByIdAddressesByAddressIdRequest.


        :param country: The country of this PatchApiUsersByIdAddressesByAddressIdRequest.
        :type country: str
        """
        if country is not None and len(country) > 100:
            raise ValueError("Invalid value for `country`, length must be less than or equal to `100`")  # noqa: E501

        self._country = country

    @property
    def is_default(self) -> PostApiUsersByIdAddressesRequestIsDefault:
        """Gets the is_default of this PatchApiUsersByIdAddressesByAddressIdRequest.


        :return: The is_default of this PatchApiUsersByIdAddressesByAddressIdRequest.
        :rtype: PostApiUsersByIdAddressesRequestIsDefault
        """
        return self._is_default

    @is_default.setter
    def is_default(self, is_default: PostApiUsersByIdAddressesRequestIsDefault):
        """Sets the is_default of this PatchApiUsersByIdAddressesByAddressIdRequest.


        :param is_default: The is_default of this PatchApiUsersByIdAddressesByAddressIdRequest.
        :type is_default: PostApiUsersByIdAddressesRequestIsDefault
        """

        self._is_default = is_default

    @property
    def created_at(self) -> str:
        """Gets the created_at of this PatchApiUsersByIdAddressesByAddressIdRequest.


        :return: The created_at of this PatchApiUsersByIdAddressesByAddressIdRequest.
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: str):
        """Sets the created_at of this PatchApiUsersByIdAddressesByAddressIdRequest.


        :param created_at: The created_at of this PatchApiUsersByIdAddressesByAddressIdRequest.
        :type created_at: str
        """

        self._created_at = created_at

    @property
    def updated_at(self) -> str:
        """Gets the updated_at of this PatchApiUsersByIdAddressesByAddressIdRequest.


        :return: The updated_at of this PatchApiUsersByIdAddressesByAddressIdRequest.
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: str):
        """Sets the updated_at of this PatchApiUsersByIdAddressesByAddressIdRequest.


        :param updated_at: The updated_at of this PatchApiUsersByIdAddressesByAddressIdRequest.
        :type updated_at: str
        """

        self._updated_at = updated_at
