from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.post_api_users_by_id_addresses201_response_address import PostApiUsersByIdAddresses201ResponseAddress
from openapi_server import util

from openapi_server.models.post_api_users_by_id_addresses201_response_address import PostApiUsersByIdAddresses201ResponseAddress  # noqa: E501

class PostApiUsersByIdAddresses201Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, address=None):  # noqa: E501
        """PostApiUsersByIdAddresses201Response - a model defined in OpenAPI

        :param address: The address of this PostApiUsersByIdAddresses201Response.  # noqa: E501
        :type address: PostApiUsersByIdAddresses201ResponseAddress
        """
        self.openapi_types = {
            'address': PostApiUsersByIdAddresses201ResponseAddress
        }

        self.attribute_map = {
            'address': 'address'
        }

        self._address = address

    @classmethod
    def from_dict(cls, dikt) -> 'PostApiUsersByIdAddresses201Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The postApiUsersByIdAddresses_201_response of this PostApiUsersByIdAddresses201Response.  # noqa: E501
        :rtype: PostApiUsersByIdAddresses201Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def address(self) -> PostApiUsersByIdAddresses201ResponseAddress:
        """Gets the address of this PostApiUsersByIdAddresses201Response.


        :return: The address of this PostApiUsersByIdAddresses201Response.
        :rtype: PostApiUsersByIdAddresses201ResponseAddress
        """
        return self._address

    @address.setter
    def address(self, address: PostApiUsersByIdAddresses201ResponseAddress):
        """Sets the address of this PostApiUsersByIdAddresses201Response.


        :param address: The address of this PostApiUsersByIdAddresses201Response.
        :type address: PostApiUsersByIdAddresses201ResponseAddress
        """
        if address is None:
            raise ValueError("Invalid value for `address`, must not be `None`")  # noqa: E501

        self._address = address
