from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class PostApiUsersByIdAddresses201ResponseAddress(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, user_id=None, address=None, phone=None, state=None, postal_code=None, country=None, is_default=None, created_at=None, updated_at=None):  # noqa: E501
        """PostApiUsersByIdAddresses201ResponseAddress - a model defined in OpenAPI

        :param id: The id of this PostApiUsersByIdAddresses201ResponseAddress.  # noqa: E501
        :type id: int
        :param user_id: The user_id of this PostApiUsersByIdAddresses201ResponseAddress.  # noqa: E501
        :type user_id: int
        :param address: The address of this PostApiUsersByIdAddresses201ResponseAddress.  # noqa: E501
        :type address: str
        :param phone: The phone of this PostApiUsersByIdAddresses201ResponseAddress.  # noqa: E501
        :type phone: str
        :param state: The state of this PostApiUsersByIdAddresses201ResponseAddress.  # noqa: E501
        :type state: str
        :param postal_code: The postal_code of this PostApiUsersByIdAddresses201ResponseAddress.  # noqa: E501
        :type postal_code: str
        :param country: The country of this PostApiUsersByIdAddresses201ResponseAddress.  # noqa: E501
        :type country: str
        :param is_default: The is_default of this PostApiUsersByIdAddresses201ResponseAddress.  # noqa: E501
        :type is_default: int
        :param created_at: The created_at of this PostApiUsersByIdAddresses201ResponseAddress.  # noqa: E501
        :type created_at: str
        :param updated_at: The updated_at of this PostApiUsersByIdAddresses201ResponseAddress.  # noqa: E501
        :type updated_at: str
        """
        self.openapi_types = {
            'id': int,
            'user_id': int,
            'address': str,
            'phone': str,
            'state': str,
            'postal_code': str,
            'country': str,
            'is_default': int,
            'created_at': str,
            'updated_at': str
        }

        self.attribute_map = {
            'id': 'id',
            'user_id': 'user_id',
            'address': 'address',
            'phone': 'phone',
            'state': 'state',
            'postal_code': 'postal_code',
            'country': 'country',
            'is_default': 'is_default',
            'created_at': 'created_at',
            'updated_at': 'updated_at'
        }

        self._id = id
        self._user_id = user_id
        self._address = address
        self._phone = phone
        self._state = state
        self._postal_code = postal_code
        self._country = country
        self._is_default = is_default
        self._created_at = created_at
        self._updated_at = updated_at

    @classmethod
    def from_dict(cls, dikt) -> 'PostApiUsersByIdAddresses201ResponseAddress':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The postApiUsersByIdAddresses_201_response_address of this PostApiUsersByIdAddresses201ResponseAddress.  # noqa: E501
        :rtype: PostApiUsersByIdAddresses201ResponseAddress
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this PostApiUsersByIdAddresses201ResponseAddress.


        :return: The id of this PostApiUsersByIdAddresses201ResponseAddress.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this PostApiUsersByIdAddresses201ResponseAddress.


        :param id: The id of this PostApiUsersByIdAddresses201ResponseAddress.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501
        if id is not None and id > 9007199254740991:  # noqa: E501
            raise ValueError("Invalid value for `id`, must be a value less than or equal to `9007199254740991`")  # noqa: E501
        if id is not None and id < -9007199254740991:  # noqa: E501
            raise ValueError("Invalid value for `id`, must be a value greater than or equal to `-9007199254740991`")  # noqa: E501

        self._id = id

    @property
    def user_id(self) -> int:
        """Gets the user_id of this PostApiUsersByIdAddresses201ResponseAddress.


        :return: The user_id of this PostApiUsersByIdAddresses201ResponseAddress.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this PostApiUsersByIdAddresses201ResponseAddress.


        :param user_id: The user_id of this PostApiUsersByIdAddresses201ResponseAddress.
        :type user_id: int
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501
        if user_id is not None and user_id > 9007199254740991:  # noqa: E501
            raise ValueError("Invalid value for `user_id`, must be a value less than or equal to `9007199254740991`")  # noqa: E501
        if user_id is not None and user_id < -9007199254740991:  # noqa: E501
            raise ValueError("Invalid value for `user_id`, must be a value greater than or equal to `-9007199254740991`")  # noqa: E501

        self._user_id = user_id

    @property
    def address(self) -> str:
        """Gets the address of this PostApiUsersByIdAddresses201ResponseAddress.


        :return: The address of this PostApiUsersByIdAddresses201ResponseAddress.
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address: str):
        """Sets the address of this PostApiUsersByIdAddresses201ResponseAddress.


        :param address: The address of this PostApiUsersByIdAddresses201ResponseAddress.
        :type address: str
        """
        if address is None:
            raise ValueError("Invalid value for `address`, must not be `None`")  # noqa: E501

        self._address = address

    @property
    def phone(self) -> str:
        """Gets the phone of this PostApiUsersByIdAddresses201ResponseAddress.


        :return: The phone of this PostApiUsersByIdAddresses201ResponseAddress.
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone: str):
        """Sets the phone of this PostApiUsersByIdAddresses201ResponseAddress.


        :param phone: The phone of this PostApiUsersByIdAddresses201ResponseAddress.
        :type phone: str
        """
        if phone is None:
            raise ValueError("Invalid value for `phone`, must not be `None`")  # noqa: E501

        self._phone = phone

    @property
    def state(self) -> str:
        """Gets the state of this PostApiUsersByIdAddresses201ResponseAddress.


        :return: The state of this PostApiUsersByIdAddresses201ResponseAddress.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state: str):
        """Sets the state of this PostApiUsersByIdAddresses201ResponseAddress.


        :param state: The state of this PostApiUsersByIdAddresses201ResponseAddress.
        :type state: str
        """
        if state is None:
            raise ValueError("Invalid value for `state`, must not be `None`")  # noqa: E501

        self._state = state

    @property
    def postal_code(self) -> str:
        """Gets the postal_code of this PostApiUsersByIdAddresses201ResponseAddress.


        :return: The postal_code of this PostApiUsersByIdAddresses201ResponseAddress.
        :rtype: str
        """
        return self._postal_code

    @postal_code.setter
    def postal_code(self, postal_code: str):
        """Sets the postal_code of this PostApiUsersByIdAddresses201ResponseAddress.


        :param postal_code: The postal_code of this PostApiUsersByIdAddresses201ResponseAddress.
        :type postal_code: str
        """
        if postal_code is None:
            raise ValueError("Invalid value for `postal_code`, must not be `None`")  # noqa: E501

        self._postal_code = postal_code

    @property
    def country(self) -> str:
        """Gets the country of this PostApiUsersByIdAddresses201ResponseAddress.


        :return: The country of this PostApiUsersByIdAddresses201ResponseAddress.
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country: str):
        """Sets the country of this PostApiUsersByIdAddresses201ResponseAddress.


        :param country: The country of this PostApiUsersByIdAddresses201ResponseAddress.
        :type country: str
        """
        if country is None:
            raise ValueError("Invalid value for `country`, must not be `None`")  # noqa: E501

        self._country = country

    @property
    def is_default(self) -> int:
        """Gets the is_default of this PostApiUsersByIdAddresses201ResponseAddress.


        :return: The is_default of this PostApiUsersByIdAddresses201ResponseAddress.
        :rtype: int
        """
        return self._is_default

    @is_default.setter
    def is_default(self, is_default: int):
        """Sets the is_default of this PostApiUsersByIdAddresses201ResponseAddress.


        :param is_default: The is_default of this PostApiUsersByIdAddresses201ResponseAddress.
        :type is_default: int
        """
        if is_default is None:
            raise ValueError("Invalid value for `is_default`, must not be `None`")  # noqa: E501
        if is_default is not None and is_default > 9007199254740991:  # noqa: E501
            raise ValueError("Invalid value for `is_default`, must be a value less than or equal to `9007199254740991`")  # noqa: E501
        if is_default is not None and is_default < -9007199254740991:  # noqa: E501
            raise ValueError("Invalid value for `is_default`, must be a value greater than or equal to `-9007199254740991`")  # noqa: E501

        self._is_default = is_default

    @property
    def created_at(self) -> str:
        """Gets the created_at of this PostApiUsersByIdAddresses201ResponseAddress.


        :return: The created_at of this PostApiUsersByIdAddresses201ResponseAddress.
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: str):
        """Sets the created_at of this PostApiUsersByIdAddresses201ResponseAddress.


        :param created_at: The created_at of this PostApiUsersByIdAddresses201ResponseAddress.
        :type created_at: str
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def updated_at(self) -> str:
        """Gets the updated_at of this PostApiUsersByIdAddresses201ResponseAddress.


        :return: The updated_at of this PostApiUsersByIdAddresses201ResponseAddress.
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: str):
        """Sets the updated_at of this PostApiUsersByIdAddresses201ResponseAddress.


        :param updated_at: The updated_at of this PostApiUsersByIdAddresses201ResponseAddress.
        :type updated_at: str
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")  # noqa: E501

        self._updated_at = updated_at
