from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.get_api_users_offset200_response_users_inner import GetApiUsersOffset200ResponseUsersInner
from openapi_server import util

from openapi_server.models.get_api_users_offset200_response_users_inner import GetApiUsersOffset200ResponseUsersInner  # noqa: E501

class PostApiUsers201Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user=None):  # noqa: E501
        """PostApiUsers201Response - a model defined in OpenAPI

        :param user: The user of this PostApiUsers201Response.  # noqa: E501
        :type user: GetApiUsersOffset200ResponseUsersInner
        """
        self.openapi_types = {
            'user': GetApiUsersOffset200ResponseUsersInner
        }

        self.attribute_map = {
            'user': 'user'
        }

        self._user = user

    @classmethod
    def from_dict(cls, dikt) -> 'PostApiUsers201Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The postApiUsers_201_response of this PostApiUsers201Response.  # noqa: E501
        :rtype: PostApiUsers201Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self) -> GetApiUsersOffset200ResponseUsersInner:
        """Gets the user of this PostApiUsers201Response.


        :return: The user of this PostApiUsers201Response.
        :rtype: GetApiUsersOffset200ResponseUsersInner
        """
        return self._user

    @user.setter
    def user(self, user: GetApiUsersOffset200ResponseUsersInner):
        """Sets the user of this PostApiUsers201Response.


        :param user: The user of this PostApiUsers201Response.
        :type user: GetApiUsersOffset200ResponseUsersInner
        """
        if user is None:
            raise ValueError("Invalid value for `user`, must not be `None`")  # noqa: E501

        self._user = user
