from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class PostApiUsersRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, email=None, username=None, password=None, first_name=None, last_name=None, dob=None):  # noqa: E501
        """PostApiUsersRequest - a model defined in OpenAPI

        :param email: The email of this PostApiUsersRequest.  # noqa: E501
        :type email: str
        :param username: The username of this PostApiUsersRequest.  # noqa: E501
        :type username: str
        :param password: The password of this PostApiUsersRequest.  # noqa: E501
        :type password: str
        :param first_name: The first_name of this PostApiUsersRequest.  # noqa: E501
        :type first_name: str
        :param last_name: The last_name of this PostApiUsersRequest.  # noqa: E501
        :type last_name: str
        :param dob: The dob of this PostApiUsersRequest.  # noqa: E501
        :type dob: date
        """
        self.openapi_types = {
            'email': str,
            'username': str,
            'password': str,
            'first_name': str,
            'last_name': str,
            'dob': date
        }

        self.attribute_map = {
            'email': 'email',
            'username': 'username',
            'password': 'password',
            'first_name': 'first_name',
            'last_name': 'last_name',
            'dob': 'dob'
        }

        self._email = email
        self._username = username
        self._password = password
        self._first_name = first_name
        self._last_name = last_name
        self._dob = dob

    @classmethod
    def from_dict(cls, dikt) -> 'PostApiUsersRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The postApiUsers_request of this PostApiUsersRequest.  # noqa: E501
        :rtype: PostApiUsersRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def email(self) -> str:
        """Gets the email of this PostApiUsersRequest.


        :return: The email of this PostApiUsersRequest.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this PostApiUsersRequest.


        :param email: The email of this PostApiUsersRequest.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def username(self) -> str:
        """Gets the username of this PostApiUsersRequest.


        :return: The username of this PostApiUsersRequest.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this PostApiUsersRequest.


        :param username: The username of this PostApiUsersRequest.
        :type username: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501
        if username is not None and len(username) > 30:
            raise ValueError("Invalid value for `username`, length must be less than or equal to `30`")  # noqa: E501
        if username is not None and len(username) < 5:
            raise ValueError("Invalid value for `username`, length must be greater than or equal to `5`")  # noqa: E501

        self._username = username

    @property
    def password(self) -> str:
        """Gets the password of this PostApiUsersRequest.


        :return: The password of this PostApiUsersRequest.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this PostApiUsersRequest.


        :param password: The password of this PostApiUsersRequest.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501
        if password is not None and len(password) < 6:
            raise ValueError("Invalid value for `password`, length must be greater than or equal to `6`")  # noqa: E501

        self._password = password

    @property
    def first_name(self) -> str:
        """Gets the first_name of this PostApiUsersRequest.


        :return: The first_name of this PostApiUsersRequest.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name: str):
        """Sets the first_name of this PostApiUsersRequest.


        :param first_name: The first_name of this PostApiUsersRequest.
        :type first_name: str
        """
        if first_name is None:
            raise ValueError("Invalid value for `first_name`, must not be `None`")  # noqa: E501
        if first_name is not None and len(first_name) > 50:
            raise ValueError("Invalid value for `first_name`, length must be less than or equal to `50`")  # noqa: E501
        if first_name is not None and len(first_name) < 1:
            raise ValueError("Invalid value for `first_name`, length must be greater than or equal to `1`")  # noqa: E501

        self._first_name = first_name

    @property
    def last_name(self) -> str:
        """Gets the last_name of this PostApiUsersRequest.


        :return: The last_name of this PostApiUsersRequest.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name: str):
        """Sets the last_name of this PostApiUsersRequest.


        :param last_name: The last_name of this PostApiUsersRequest.
        :type last_name: str
        """
        if last_name is None:
            raise ValueError("Invalid value for `last_name`, must not be `None`")  # noqa: E501
        if last_name is not None and len(last_name) > 50:
            raise ValueError("Invalid value for `last_name`, length must be less than or equal to `50`")  # noqa: E501
        if last_name is not None and len(last_name) < 1:
            raise ValueError("Invalid value for `last_name`, length must be greater than or equal to `1`")  # noqa: E501

        self._last_name = last_name

    @property
    def dob(self) -> date:
        """Gets the dob of this PostApiUsersRequest.


        :return: The dob of this PostApiUsersRequest.
        :rtype: date
        """
        return self._dob

    @dob.setter
    def dob(self, dob: date):
        """Sets the dob of this PostApiUsersRequest.


        :param dob: The dob of this PostApiUsersRequest.
        :type dob: date
        """

        self._dob = dob
