from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class PostApiAuthLogout200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, ok=None):  # noqa: E501
        """PostApiAuthLogout200Response - a model defined in OpenAPI

        :param ok: The ok of this PostApiAuthLogout200Response.  # noqa: E501
        :type ok: bool
        """
        self.openapi_types = {
            'ok': bool
        }

        self.attribute_map = {
            'ok': 'ok'
        }

        self._ok = ok

    @classmethod
    def from_dict(cls, dikt) -> 'PostApiAuthLogout200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The postApiAuthLogout_200_response of this PostApiAuthLogout200Response.  # noqa: E501
        :rtype: PostApiAuthLogout200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ok(self) -> bool:
        """Gets the ok of this PostApiAuthLogout200Response.


        :return: The ok of this PostApiAuthLogout200Response.
        :rtype: bool
        """
        return self._ok

    @ok.setter
    def ok(self, ok: bool):
        """Sets the ok of this PostApiAuthLogout200Response.


        :param ok: The ok of this PostApiAuthLogout200Response.
        :type ok: bool
        """
        if ok is None:
            raise ValueError("Invalid value for `ok`, must not be `None`")  # noqa: E501

        self._ok = ok
